add_newline = false
command_timeout = 3000

[kubernetes]
disabled = false
style = 'blue'
format = '[$symbol$context@$cluster( \($namespace\))]($style) in '

[directory]
style = 'green'
truncate_to_repo = false

[jobs]
symbol_threshold = 1

[gcloud]
disabled = true

[docker_context]
disabled = true

[aws]
disabled = true

[golang]
disabled = true

# if proxy variables are set, display them
[env_var.HTTPS_PROXY]
[env_var.HTTP_PROXY]

