add_newline = false
command_timeout = 3000

[kubernetes]
disabled = false
style = 'blue'
format = '[$symbol$context@$cluster( \($namespace\))]($style) in '

[directory]
style = 'green'
truncate_to_repo = false

[jobs]
threshold = 2
